version: '3.8'
services:

# application properties:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: house_prices
    # '/start' is the shell script used to run the service
    depends_on:
      - db
    volumes:
      - .:/app
    environment:
      - UWSGI_PY_AUTORELOAD=1 # development only
    env_file:
      - .env
    ports:
      - 8000:8000

# postgres database properties:
  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
    restart: always

volumes:
  postgres_data:
