# Generated by Django 4.1.6 on 2023-02-09 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_1', models.CharField(max_length=128)),
                ('field_2', models.CharField(max_length=128)),
                ('field_3', models.CharField(max_length=128)),
                ('field_4', models.CharField(max_length=128)),
                ('field_5', models.CharField(max_length=128)),
                ('field_6', models.CharField(max_length=128)),
                ('field_7', models.CharField(max_length=128)),
                ('field_8', models.CharField(max_length=128)),
                ('field_9', models.CharField(max_length=128)),
                ('field_10', models.CharField(max_length=128)),
                ('field_11', models.CharField(max_length=128)),
                ('field_12', models.CharField(max_length=128)),
                ('field_13', models.CharField(max_length=128)),
                ('field_14', models.CharField(max_length=128)),
                ('field_15', models.CharField(max_length=128)),
                ('field_16', models.CharField(max_length=128)),
            ],
        ),
    ]
